"""add_user_group_relationship

Revision ID: 85ab58fc22e6
Revises: 01e190bd2b55
Create Date: 2025-11-26 16:51:14.158498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ab58fc22e6'
down_revision: Union[str, Sequence[str], None] = '01e190bd2b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    
    # Drop existing groups data to avoid conversion issues
    op.execute('DELETE FROM groups')
    
    # Now alter the column type with USING clause for safe conversion
    op.execute('ALTER TABLE groups ALTER COLUMN created_by TYPE INTEGER USING created_by::integer')
    
    op.create_foreign_key(None, 'groups', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.alter_column('groups', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('user_group_association')
    # ### end Alembic commands ###
